[package]
name = "sylvie"
version.workspace = true
license.workspace = true
edition.workspace = true

[lib]
name = "sylvie"
path = "src/lib.rs"

[[bin]]
name = "sylvie"
path = "src/main.rs"

[dependencies]
sylvie-core.workspace = true
clap.workspace = true
dirs.workspace = true
futures-util.workspace = true
indicatif.workspace = true
opaque-ke.workspace = true
reqwest.workspace = true
rpassword.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml.workspace = true

[dev-dependencies]
sylver = { path = "../server" }
uuid.workspace = true
