[package]
name = "sylver"
version.workspace = true
license.workspace = true
edition.workspace = true

[[bin]]
name = "sylver"
path = "src/main.rs"

[dependencies]
sylvie-core.workspace = true
axum.workspace = true
base64.workspace = true
opaque-ke.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
time.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
dirs.workspace = true
pardeh = { git = "https://github.com/liagha/pardeh", rev = "06d80d3bc1934a6a52d730ec3891299e2b9f457a" }

[dev-dependencies]
reqwest.workspace = true
uuid.workspace = true
sylvie-web = { path = "../web" }
